# Generated by Django 3.0 on 2022-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='название')),
                ('description_short', models.CharField(max_length=1000, verbose_name='короткое описание')),
                ('description_long', models.TextField(verbose_name='длинное описание')),
                ('coordinates', models.TextField(verbose_name='координаты')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'db_table': 'Plaases',
            },
        ),
    ]
