# Generated by Django 3.0 on 2022-06-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_poster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='places/', verbose_name='изображение')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where_to_go_poster.Places', verbose_name='место')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'db_table': 'ImagesPlaces',
            },
        ),
    ]
