# Generated by Django 4.0.5 on 2022-06-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_poster', '0002_imagesplaces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesplaces',
            options={'ordering': ['id'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
