# Generated by Django 4.0.5 on 2022-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_poster', '0003_alter_imagesplaces_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesplaces',
            options={'ordering': ('img_order',), 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AddField(
            model_name='imagesplaces',
            name='img_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
