# Generated by Django 4.0.5 on 2022-06-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_poster', '0004_alter_imagesplaces_options_imagesplaces_img_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'ordering': ('place_order',), 'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.AddField(
            model_name='places',
            name='place_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
