# Generated by Django 4.0.5 on 2022-06-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_poster', '0005_alter_places_options_places_place_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='places',
            table='Places',
        ),
    ]
