# Generated by Django 3.0 on 2022-06-09 18:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_poster', '0007_auto_20220605_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='длинное описание'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='короткое описание'),
        ),
        migrations.AlterField(
            model_name='places',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
    ]
