# Generated by Django 3.0 on 2022-06-15 15:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_poster', '0008_auto_20220609_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='длинное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='короткое описание'),
        ),
    ]
