# Generated by Django 3.0 on 2022-06-17 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_poster', '0010_auto_20220615_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesplaces',
            options={'ordering': ('order',), 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.RenameField(
            model_name='imagesplaces',
            old_name='img_order',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='imagesplaces',
            name='img',
            field=models.ImageField(upload_to='places/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='imagesplaces',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='where_to_go_poster.Places', verbose_name='место'),
        ),
    ]
