# Generated by Django 3.0 on 2022-06-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_poster', '0011_auto_20220617_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.RemoveField(
            model_name='places',
            name='place_order',
        ),
    ]
